### ISSUE TITLE
How to test with new word input for chars.py

### ISSUE THREAD

**Issue by NiubilityDiu** [pbloem/language-models#5]
Hello,

I am very new to the statistical language model, and I am glad that you upload an example to the Github. However, I have trouble compiling your chars.py file.

The model fitting and training were fine to me, but I was wondering how to test the fitting model with new data input?

Can you provide a command syntax for illustration?

For example, suppose that I already have 'b' and 'r', and I want to spell the word 'brain', what command should I type in order to see the next possible character?

Finally, I was wondering if your model can output the probability distribution of the next possible character?

Thanks in advance.

**Comment by pbloem** [comment]
Hi, it's been a while since I wrote this code (or used Keras), but I think the easiest thing is to create a seed sequence (a list of integers representing characters) and call the generate_seq function with the trained model. This will continue to generate characters with the model. 

The `probs` vector on line 48 contains the output probabilities of the next character on each token, so you should be able to get out the information you want by manipulating this function a little.

**Comment by NiubilityDiu** [comment]
Thank you for your clarification!

Thanks,
Tianwen Ma (he/him/his)
Ph.D. Candidate in Biostatistics
Graduate Student Research Assistant
School of Public Health
University of Michigan
***@***.*** | (857)265-8064
「人生には３つの坂があるそうです。上り坂、下り坂、まさか」
